/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as GameGameIDRouteImport } from './routes/game/$gameID'
import { Route as AuthenticatedLobbyLobbyIDRouteImport } from './routes/_authenticated/lobby/$lobbyID'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const GameGameIDRoute = GameGameIDRouteImport.update({
  id: '/game/$gameID',
  path: '/game/$gameID',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLobbyLobbyIDRoute =
  AuthenticatedLobbyLobbyIDRouteImport.update({
    id: '/lobby/$lobbyID',
    path: '/lobby/$lobbyID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/game/$gameID': typeof GameGameIDRoute
  '/': typeof AuthenticatedIndexRoute
  '/game': typeof GameIndexRoute
  '/lobby/$lobbyID': typeof AuthenticatedLobbyLobbyIDRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/game/$gameID': typeof GameGameIDRoute
  '/': typeof AuthenticatedIndexRoute
  '/game': typeof GameIndexRoute
  '/lobby/$lobbyID': typeof AuthenticatedLobbyLobbyIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/game/$gameID': typeof GameGameIDRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/game/': typeof GameIndexRoute
  '/_authenticated/lobby/$lobbyID': typeof AuthenticatedLobbyLobbyIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/game/$gameID'
    | '/'
    | '/game'
    | '/lobby/$lobbyID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/game/$gameID'
    | '/'
    | '/game'
    | '/lobby/$lobbyID'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/game/$gameID'
    | '/_authenticated/'
    | '/game/'
    | '/_authenticated/lobby/$lobbyID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  GameGameIDRoute: typeof GameGameIDRoute
  GameIndexRoute: typeof GameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/game/$gameID': {
      id: '/game/$gameID'
      path: '/game/$gameID'
      fullPath: '/game/$gameID'
      preLoaderRoute: typeof GameGameIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lobby/$lobbyID': {
      id: '/_authenticated/lobby/$lobbyID'
      path: '/lobby/$lobbyID'
      fullPath: '/lobby/$lobbyID'
      preLoaderRoute: typeof AuthenticatedLobbyLobbyIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLobbyLobbyIDRoute: typeof AuthenticatedLobbyLobbyIDRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLobbyLobbyIDRoute: AuthenticatedLobbyLobbyIDRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  GameGameIDRoute: GameGameIDRoute,
  GameIndexRoute: GameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
